### ISSUE TITLE
Unable to read schema reference

### ISSUE THREAD

**Issue by darshak-patel** [nawaz1991/lua-oasvalidator#6]
Iua-oasvalidator is not able to validate the json schema if the schema reference is provided as part of requestBody.

**Comment by darshak-patel** [comment]
@nawaz1991 can you please provide your input?

**Comment by nawaz1991** [comment]
@darshak-patel , for now the osavalidtor expects resolved JSON. I will be updating it to resolve references.
Can you please input resolved JSON?
Use https://editor-next.swagger.io/
File -> Download Resloved JSON

**Comment by darshak-patel** [comment]
@nawaz1991 Is it possible to pass complete swagger data as a argument of .GetValidators() function instead of passing a file path?

**Comment by nawaz1991** [comment]
@darshak-patel , yes, you can provide JSON as string as well. But again, JSON should be resolved.

**Comment by darshak-patel** [comment]
@nawaz1991 can you please help?

**Comment by darshak-patel** [comment]
@nawaz1991 when I try to pass JSON as string to .GetValidators, I am getting "cannot read OAS file" error. I am using the same oasis file you have given in your data folder. If I print the content it's printing it as JSON string. Do I need to pass any flag or what? Can you please help since I am blocked?

**Comment by nawaz1991** [comment]
@darshak-patel , I have updated the cpp-oasvalidator (the base project) to handle the JSON references. 
Can you please try it gaian. I hope the issue "Cannot open OAS file" should also be resolved.

**Comment by darshak-patel** [comment]
@nawaz1991 I also noticed if OAS3 file is big after dereferencing the schema approximately around 7000 to 8000 lines then this lua-oasvalidator is throwing std:out_of_range error during .GetValidators method call

**Comment by nawaz1991** [comment]
`out_of_range` error should not be due to file size. 
Is it possible to share your file at m.nawaz2003@gmail.com?

**Comment by darshak-patel** [comment]
@nawaz1991 I found the issue why oasvalidator is throwing std:out_of_range error. The problem is adding description key at path level.

**Comment by darshak-patel** [comment]
@nawaz1991 Also it's not able to do query parameter validation correctly. Library also expecting non mandatory query parameters to be present in url.

**Comment by nawaz1991** [comment]
In base project, [cpp-oasvalidator](https://github.com/nawaz1991/cpp-oasvalidator), feature is added to resolve the JSON, if it is not resolved already.
